config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'auth/registrations', sessions: 'auth/sessions', passwords: 'auth/passwords' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'page_not_found', to: 'pages#page_not_found'
  resources :jobs do
    resources :applications, only: %i[create destroy]
  end
  resources :companies do
    resources :locations, except: :index
  end

  # my company routes
  get 'my_company', to: 'my_company#show'
  get 'my_company/recruiters', to: 'my_company#recruiters'
  get 'my_company/locations', to: 'my_company#locations'
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  has_many :applications
  has_many :users, through: :applications
  validates :title, :description, :company_id, presence: true

  def self.paginate(page)
    page = 1 if page.nil?
    offset((page.to_i - 1) * 10).limit(10)
  end

  def self.search(query)
    where('title LIKE ?', "%#{query}%") if query
  end

  def has_applicant?(user_id)
    Application.where(user_id: user_id).count.positive?
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true
class JobsController < ApplicationController
  before_action :authenticate_employer!, only: %i[new create edit update destroy]
  before_action :set_job, only: %i[show edit update destroy]

  def index
    # TODO: build pagination
    @jobs = Job.search(params[:query] || '').paginate(params[:page])
  end

  def show
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    @job.company = current_user.company
    if @job.save
      redirect_to @job
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @job.update(job_params)
      redirect_to @job
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @job.destroy
    redirect_to jobs_path, notice: 'Job was successfully deleted.'
  end

  private

  def job_params
    params.require(:job).permit(:title, :description)
  end

  def set_job
    @job = Job.find(params[:id])
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def application_by_job(job)
    (job.applications.select { |application| application.user == current_user }).first
  end

  def pages(jobs)
    (jobs / 10.0).ceil
  end
end

app/views/jobs/_form.html.erb
<%# write a form that will be used to create or update a @job %>
<%= form_with(model: @job) do |f| %>
  <% if @job.errors.any? %>
    <div>Cannot save due to <%= pluralize(@job.errors.count, 'error') %></div>
    <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<h3><%= job.title %></h3>
<% if !job.applications.count.zero? && job.has_applicant?(current_user.id) %>
  <%= button_to 'Cancel', job_application_path(job, application_by_job(job)), method: :delete %>
<% elsif current_user.role.name == 'applicant' %>
  <%= button_to 'Apply', job_applications_path(job), method: :post %>
<% elsif !current_user.company_id.nil? && job.company_id == current_user.company_id %>
  <%= button_to 'Edit', job_path(job), method: :get %>
<% end %>

app/views/jobs/edit.html.erb
<h2>Edit Job</h2>

<%= render 'form' %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>

<% @jobs.each do |job| %>
  <%= render 'job', job: job %>
<% end %>

<div class="page-selector">
  <% pages(Job.all.count).times do |page| %>
    <%= link_to page + 1, jobs_path(page: page + 1) %>
  <% end %>
</div>

<% if current_user && current_user.role.name == 'employer' %>
  <%= link_to 'New Job', new_job_path %>
<% end %>

app/views/jobs/new.html.erb
<h2>New Job</h2>

<%= render 'form' %>

app/views/jobs/show.html.erb
<h3>Job: <%= @job.title %></h3>
<p><%= @job.description %></p>
<% if @job.company == current_user.company %>
  <%= button_to 'Delete Job', job_path, method: :delete %>
<% end %>