config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'auth/registrations', sessions: 'auth/sessions', passwords: 'auth/passwords' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'page_not_found', to: 'pages#page_not_found'
  resources :jobs do
    resources :applications, only: %i[create destroy]
  end
  resources :companies do
    resources :locations, except: :index
  end

  # my company routes
  get 'my_company', to: 'my_company#show'
  get 'my_company/recruiters', to: 'my_company#recruiters'
  get 'my_company/locations', to: 'my_company#locations'
end

app/views/shared/_navbar.html.erb
<ul>
  <% if current_user.nil? %>
    <li><%= link_to 'Login', new_user_session_path %></li>
    <li><%= link_to 'Sign Up', new_user_registration_path %></li>
    <li><%= link_to 'Company Sign Up', new_company_path %></li>
  <% else %>
  <% if current_user.role.name == 'company_admin' %>
    <li><%= link_to 'My Company', my_company_path %></li>
  <% end %>
  <li><%= link_to 'Companies', companies_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, data: {'turbo-method': :delete} %></li>
  <% end %>
  <li><%= link_to 'Jobs', jobs_path %></li>


  <%# search component %>
  <li><%= render 'shared/search'%></li>
</ul>

app/views/shared/_search.html.erb
<div class="search-input">
  <%= form_tag jobs_path, method: :get do %>
    <%= text_field_tag :query, params[:query], placeholder: "Search" %>
    <%= submit_tag "Search", name: nil %>
  <% end %>
</div>