config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'auth/registrations', sessions: 'auth/sessions', passwords: 'auth/passwords' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'page_not_found', to: 'pages#page_not_found'
  resources :jobs do
    resources :applications, only: %i[create destroy]
  end
  resources :companies do
    resources :locations, except: :index
  end

  # my company routes
  get 'my_company', to: 'my_company#show'
  get 'my_company/recruiters', to: 'my_company#recruiters'
  get 'my_company/locations', to: 'my_company#locations'
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :jobs
  has_many :locations
  accepts_nested_attributes_for :locations, :users
  validates :name, presence: true
end

app/controllers/companies_controller.rb
# frozen_string_literal: true
class CompaniesController < ApplicationController
  include ApplicationHelper
  before_action :set_company, only: %i[show edit update destroy]
  before_action :authenticate_company_admin!, only: %i[edit update destroy]
  before_action :no_current_user?, only: %i[new create]

  # GET /companies
  def index
    @companies = Company.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
    @company.locations.build
    @company.users.build
  end

  # GET /companies/1/edit
  def edit
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @company.destroy
    redirect_to companies_path, notice: 'Company was successfully deleted.'
  end

  private

  def set_company
    begin
      @company = Company.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to page_not_found_path
    end
  end

  def company_params
    params.require(:company).permit(:name, locations_attributes: %i[address city state zip_code primary_location], users_attributes: %i[email password password_confirmation role_id])
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  
end

app/views/companies/_company.html.erb
<h3>Company Title: <%= company.name %></h3>
<%= link_to 'Show Company', company_path(company) %>

app/views/companies/_location_subform.html.erb
<div class="field">
  <%= location_subform.label :address %>
  <%= location_subform.text_field :address %>
</div>

<div class="field">
  <%= location_subform.label :city %>
  <%= location_subform.text_field :city %>
</div>

<div class="field">
  <%= location_subform.label :state %>
  <%= location_subform.text_field :state %>
</div>

<div class="field">
  <%= location_subform.label :zip_code %>
  <%= location_subform.text_field :zip_code %>
</div>

<div class="field">
  <%= location_subform.label :primary_location, 'Primary Location' %>
  <%= location_subform.check_box :primary_location %>
</div>

app/views/companies/edit.html.erb
<%# TODO: need to be able to add a remove new recruiters from here. %>

<%= form_with model: @company do |form| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2>Unable to save due to <%= pluralize(@company.errors.count, 'error') %></h2>
    </div>
    <ul>
    <% @company.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
<% end %>

app/views/companies/index.html.erb
<h1>Companies</h1>

<% @companies.each do |company| %>
  <%= render 'company', company: company %>
<% end %>

app/views/companies/new.html.erb
<%= form_with(model: @company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Company Name' %>
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :locations do |location_subform| %>
    <h3>Create Company Location</h3>
    <%= render 'location_subform', location_subform: location_subform %>
  <% end %>

  <%= f.fields_for :users do |user_subform| %>
    <h3>Create Company User</h3>
    <div class="field">
      <%= user_subform.label :email %>
      <%= user_subform.text_field :email %>
    </div>

    <div class="field">
      <%= user_subform.label :password %>
      <%= user_subform.password_field :password %>
    </div>

    <div class="field">
      <%= user_subform.label :password_confirmation %>
      <%= user_subform.password_field :password_confirmation %>
    </div>

    <div class="field">
      <%= user_subform.hidden_field :role_id, value: '3' %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/show.html.erb
<h2>Company: <%= @company.name %></h2>
<%= link_to 'Back to Companies', companies_path %>