config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'auth/registrations', sessions: 'auth/sessions', passwords: 'auth/passwords' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'page_not_found', to: 'pages#page_not_found'
  resources :jobs do
    resources :applications, only: %i[create destroy]
  end
  resources :companies do
    resources :locations, except: :index
  end

  # my company routes
  get 'my_company', to: 'my_company#show'
  get 'my_company/recruiters', to: 'my_company#recruiters'
  get 'my_company/locations', to: 'my_company#locations'
end

app/controllers/my_company_controller.rb
# this controller is used for company admins to make changes to their companies
class MyCompanyController < ApplicationController
  before_action :authenticate_company_admin!
  before_action :set_company

  def show
  end

  def recruiters
    @recruiters = @company.users.where(role_id: 2)
  end

  def locations
    @locations = @company.locations
  end

  private 

  def set_company
    @company = current_user.company
  end
end

app/views/my_company/_location.html.erb
<div class="location">
  <h3>Address: <%= location.address %></h3>
  <p>City: <%= location.city %></p>
  <p>State: <%= location.state %></p>
  <p>Zip: <%= location.zip_code %></p>
  <%= button_to 'Edit', edit_company_location_path(@company, location), method: :get %>
  <%= button_to 'Delete', company_location_path(@company, location), method: :delete %>
</div>

app/views/my_company/_recruiter.html.erb
<div class="recruiter">
  <h2>Email: <%= recruiter.email %></h2>
  <%= button_to 'Remove', user_path(recruiter), method: :delete %>
</div>

app/views/my_company/locations.html.erb
<h1>Locations</h1>
<%# show locations here but redirect to locations controller for creating new ones and editing %>
<div class="locations">
  <% @locations.each do |location| %>
    <%= render 'location', location: location %>
  <% end %>
</div>

app/views/my_company/recruiters.html.erb
<h1>Recruiters</h1>

<% @recruiters.each do |recruiter| %>
  <%= render 'recruiter', recruiter: recruiter %>
<% end %>

app/views/my_company/show.html.erb
<h1>My Company</h1>

<h3>Make Changes</h3>
<ul>
  <li><%= link_to 'Recruiters', my_company_recruiters_path %></li>
  <li><%= link_to 'Locations', my_company_locations_path %></li>
</ul>